### ISSUE TITLE
How to handle minor changes

### ISSUE THREAD

**Issue by pbrisbin** [freckle/stackage-snapshots#4]
[Originally raised in #3]

We often make a minor change to a snapshot without changing its base resolver. For example, moving a single Hackage or Git dep up (in version or sha) to get a fix or new feature we need. Should we do those "in-place" or should we consider a given snapshot immutable once it hits `main` and require these changes happen as a new snapshot?

In-place is easier, fewer steps for everyone involved, but the concern is that stack may not see in-place changes if it's doing any caching of the file based on URL. If that's going on, you may run into it locally but not on CI, on CI but not locally, nowhere but on deploy, etc. I have not seen evidence of caching, and `stack` may in fact download the file every single time it's invoked. This could be worth confirming, because if that's the case there is little risk to in-place modification. On the other hand, even if it caches nothing right now, it would be reasonable for it to do so _some day_, so we may want to consider things immutable from the start anyway.

If we considered things immutable, we have a few options, none great:

1. Just keep creating new snapshots, for example `lts/18/0/{suffix}.yaml` where we use suffix as our own naming space

   **NOTE**: `{suffix}` could just be a name, like a "flavor", or it could be orderable revisions.

   This option adds write-time maintenance for runtime clarity, which we usually prefer. I see little downside to this as policy, except that it's a high burden on very small updates, and could obscure the content of actual updates, since you have to copy the entirety of the snapshot form the last one before making your change.

1. Use branches or tags, like `resolver: .../{description}/lts/18/0.yaml`

   I could see this breaking down quickly -- are those branches/tags similarly immutable? Do we ever clean them up?

1. Let the App that needs it bring in whatever change as its own `extra-dep` in its own `stack.yaml`

   This is actually something we will probably need to do from time to time for a variety of reasons. So I don't find it unreasonable to let apps that need some fix/feature not yet in our standard snapshot, specify it themselves. This is treating ourselves no differently than we'd treat Stackage proper before.

   The procedure for releasing a new Snapshot just needs to include a step where we identify cases of this that are no longer needed and remove them. Again, this is how we do things with Stackage proper anyway, so it feels like a minor extension of that system to ourselves as upstream-intermediary.

---

Soft proposal: use 3 or 2, depending on the scenario.

- For small updates that a particular App needs, such as 1 git-dep sha or hackage-dep version, they should do it themselves
- For larger updates (many packages), or updates that we'll want to make across all or most Apps, we should utilize a new `/{suffix}.yaml` file

We may in fact never trigger the second case. New minor LTS resolvers are available quite frequently, so we can probably almost always batch our own updates into a new Snapshot on the latest resolver.

**Comment by eborden** [comment]
I'm in favor of option 1. Keeping the policy _immutable_ just provides so much consistency for little cost. I need to make a change, what should I do? Make a new snapshot. Done.

The question then becomes, what is the naming scheme? I propose prefixing with `FR` to make it clear that this is a closed domain bump.

### Main Line
```
main/lts/{major}/{minor}.yaml
```

### Freckle Patch
```
main/lts/{major}/{minor}/FR{patch}.yaml
```

### Example Tree
```
main
└── lts
     ├── 16
     │   ├── 1.yaml
     │   └── 2.yaml
     └── 17
         ├── 1.yaml
         ├── 1
         │   ├── FR1.yaml
         │   └── FR2.yaml
         └── 2.yaml
```

**Comment by pbrisbin** [comment]
I agree with this design overall, so let's poke that the `FR{patch}` suggestion.

I think your `{patch}` implies order and a sense that "FR2 came after / builds on FR1". For example, if `FR1` added `esqueleto-1.2`, it would be surprising if the "newer" `FR2` removed it, or added `esqueleto-1.1`. Does that align with your intent?

An alternative is forego any relation to each other. `FResqueleto` may only add `esqueleto-1.2` while `FRamazonka` might get you `amazonka@abc123`. This would be analogous installing `ghc-8.10.5.tinfo6` on Arch. I honestly don't know which I'd prefer, it probably doesn't matter in practice.

My other question is why the `FR` prefix? Isn't this entire repository a closed FR domain? What would be a patch level bump that's _not_ deserving of the FR prefix?

**Comment by eborden** [comment]
> I think your {patch} implies order and a sense that "FR2 came after / builds on FR1".

Yes, `{patch}` is a monotonic numeral expressing order. You could also call it `{revision}`.

> My other question is why the FR prefix?

This is just to signal to future readers that this `{patch|revision}` is not part of the original LTS versioning scheme and Freckle independent. That way they don't go looking for `17.10.3` on stackage and get confused when they can't find it.

**Comment by pbrisbin** [comment]
All SGTM. If AJ is on board, I'll add it to the `README`.

Note that, IMO, this still applies:

> We may in fact never trigger [this approach you've outlined]. New minor LTS resolvers are available quite frequently, so we can probably almost always batch our own updates into a new Snapshot on the latest resolver.

In other words, if you need bump `frontrow-app` to a newer commit, there would be no reason to do it as `lts/18/0/FR1.yaml` since you could just make `lts/18/2.yaml` now and include it there. Right?

**Comment by eborden** [comment]
> In other words, if you are looking to bump frontrow-app to a newer commit, there would be no reason to do it as lts/18/0/FR1.yaml since you could just make lts/18/2.yaml now and include it there. Right?

Totally

**Comment by z0isch** [comment]
This all sounds good to me! So the idea would be to use a `lts/18/0/FR1.yaml` until we move to the next minor LTS bump and then include the changes from `FR1` in `lts/18/1.yaml` for example?

**Comment by pbrisbin** [comment]
Yup!
